name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: "1.26"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Run Trivy vulnerability scanner on source code
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v4
        with:
          sarif_file: "trivy-results.sarif"

      - name: Run Gosec Security Scanner
        uses: securego/gosec@45b083a0cb42119d61b1e0e364d8c62c68f6f5cd # master
        with:
          args: "-no-fail -fmt sarif -out gosec-results.sarif ./..."

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v4
        with:
          sarif_file: gosec-results.sarif
